LootJS.modifiers(event => {
    event.addBlockModifier("tectonica:sample_ore")
        .addLoot(LootEntry.of("tectonica:basic_raw_sample")
            .matchTool(ItemFilter.not(ItemFilter.hasEnchantment("minecraft:silk_touch", 1)))
            .setCount([1, 3])
            .applyOreBonus("minecraft:fortune")
        )
        .addLoot(LootEntry.of("tectonica:sample_ore")
            .matchTool(ItemFilter.hasEnchantment("minecraft:silk_touch", 1))
        )
})