StartupEvents.registry("block", event => {
    event.create("tectonica:reactor_casing")
        .parentModel("tectonica:block/reactor_casing")
        .soundType("metal")
        .hardness(3.0)
        .resistance(10.0)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock("tectonica:reactor_casings")

    event.create("tectonica:reactor_glass")
        .parentModel("tectonica:block/reactor_glass")
        .soundType("glass")
        .defaultTranslucent()
        .hardness(0.3)
        .resistance(0.3)
        .tagBlock("tectonica:reactor_casings")

    event.create("tectonica:reactor_rod")
        .parentModel("tectonica:block/reactor_rod")
        .soundType("metal")
        .defaultCutout()
        .hardness(3.0)
        .resistance(10.0)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
})